In [4]:
import numpy as np

In [1]:
mylist = [1,2,3]

In [2]:
type(mylist)

list

In [5]:
np.array(mylist)


array([1, 2, 3])

In [7]:
my_matrix = [[1,2,3],[4,5,6],[7,8,9]]
my_matrix

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [8]:
np.array(my_matrix)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [10]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [12]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [13]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [14]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [17]:
np.linspace(0,10,37)

array([ 0.        ,  0.27777778,  0.55555556,  0.83333333,  1.11111111,
        1.38888889,  1.66666667,  1.94444444,  2.22222222,  2.5       ,
        2.77777778,  3.05555556,  3.33333333,  3.61111111,  3.88888889,
        4.16666667,  4.44444444,  4.72222222,  5.        ,  5.27777778,
        5.55555556,  5.83333333,  6.11111111,  6.38888889,  6.66666667,
        6.94444444,  7.22222222,  7.5       ,  7.77777778,  8.05555556,
        8.33333333,  8.61111111,  8.88888889,  9.16666667,  9.44444444,
        9.72222222, 10.        ])

In [18]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [20]:
np.random.rand(5,2)

array([[0.03683456, 0.850916  ],
       [0.14073964, 0.29021205],
       [0.3061315 , 0.4446561 ],
       [0.69597474, 0.93203697],
       [0.03425684, 0.06408952]])

In [21]:
np.random.randn(5,2)

array([[ 0.27513589, -0.54419142],
       [-2.76580843, -0.46752833],
       [-0.1309051 , -0.35909406],
       [ 0.43173371,  1.66280454],
       [ 0.89140696, -1.86447372]])

In [22]:
np.random.randint(0,20,4)

array([15, 17,  9,  8])

In [23]:
np.random.seed(42)
np.random.rand(4)

array([0.37454012, 0.95071431, 0.73199394, 0.59865848])

In [25]:
arr = np.arange(0,25)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [28]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [32]:
arrr = np.random.randint(0,101,10)
arrr

array([74, 74, 87, 99, 23,  2, 21, 52,  1, 87])

In [33]:
arrr.max()

99

In [34]:
arrr.min()

1

In [35]:
arrr.argmax()

3

In [36]:
arrr.argmin()

8

In [ ]:
import numpy as np


In [39]:
arr = np.arange(0,11)

In [40]:
arr[8]

8

In [41]:
arr[1:5]

array([1, 2, 3, 4])

In [42]:
arr[:5]

array([0, 1, 2, 3, 4])

In [43]:
arr[0:5] = 100

In [44]:
arr = np.arange(0,11)

In [45]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [46]:
arr = np.arange(0,11)

In [55]:
slice_of_arr = arr[0:5]

In [56]:
slice_of_arr

array([0, 1, 2, 3, 4])

In [57]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [58]:
slice_of_arr[:] = 99
slice_of_arr

array([99, 99, 99, 99, 99])

In [59]:
arr

array([99, 99, 99, 99, 99,  5,  6,  7,  8,  9, 10])

In [60]:
arr_copy = arr.copy()

In [62]:
arr_copy[:] = 100 
arr_copy

array([100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100])

In [63]:
arr

array([99, 99, 99, 99, 99,  5,  6,  7,  8,  9, 10])

In [64]:
arr_2d = np.array([[5,10,15],[20,25,30],[35,40,45]])
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [65]:
arr_2d.shape

(3, 3)

In [67]:
arr_2d[2,1]

40

In [68]:
arr_2d[:2]

array([[ 5, 10, 15],
       [20, 25, 30]])

In [73]:
arr_2d[:2,1:]

array([[10, 15],
       [25, 30]])

In [75]:
arr = np.arange(1,11)

In [76]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [77]:
arr > 4 

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [79]:
bool_arr = arr > 4 
bool_arr

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [80]:
arr[arr>4]

array([ 5,  6,  7,  8,  9, 10])

In [81]:
import numpy as np

In [82]:
arr = np.arange(0,10)

In [83]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [84]:
arr +5

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [85]:
arr -2 

array([-2, -1,  0,  1,  2,  3,  4,  5,  6,  7])

In [86]:
arr + arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [87]:
arr * arr

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [88]:
arr - arr 

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [89]:
arr / arr

C:\Users\pc\anaconda3\envs\my_rl_env\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [90]:
1 / 0 

ZeroDivisionError: division by zero

In [91]:
1 / arr

C:\Users\pc\anaconda3\envs\my_rl_env\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in true_divide
  """Entry point for launching an IPython kernel.


array([       inf, 1.        , 0.5       , 0.33333333, 0.25      ,
       0.2       , 0.16666667, 0.14285714, 0.125     , 0.11111111])

In [92]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [93]:
np.sin(arr)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849])

In [94]:
np.log(arr)

C:\Users\pc\anaconda3\envs\my_rl_env\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in log
  """Entry point for launching an IPython kernel.


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458])

In [95]:
arr.sum()

45

In [96]:
arr.mean()

4.5

In [98]:
arr.max()

9

In [99]:
arr.var()

8.25

In [100]:
arr.std()

2.8722813232690143

In [101]:
arr2d = np.arange(0,25).reshape(5,5)

In [102]:
arr2d.shape

(5, 5)

In [103]:
arr2d

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [104]:
arr2d.sum()

300

In [105]:
arr2d.sum(axis=0)

array([50, 55, 60, 65, 70])

In [107]:
arr2d.sum(axis=1)

array([ 10,  35,  60,  85, 110])

Exercice

In [ ]:
#1
import numpy as np

In [108]:
#2
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [110]:
#3
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [112]:
#4
cinq = np.ones(10) * 5
cinq

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

In [116]:
#5
np.arange(10,51)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50])

In [117]:
#6
np.arange(10,52,2)

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48, 50])

In [126]:
#7
seven = np.arange(0,9).reshape(3,3)
seven

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [127]:
#8
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [209]:
#9
np.random.rand(1)

array([0.92922805])

In [210]:
#10
np.random.randn(25)

array([ 0.88774846,  0.82947484, -0.19382614, -0.26451484, -2.00386236,
        0.63541803, -1.23925839,  0.05993263,  0.27737694,  1.3606586 ,
       -1.3088204 , -3.01951216,  0.18384954,  1.80051118,  1.23894635,
        0.20965942, -0.49163619,  0.8071226 , -0.9735462 ,  0.47635777,
        0.50547016,  1.06020991,  2.75966004,  0.39241597, -0.50896363])

In [250]:
#11
np.arange(1,101).reshape(10,10)/100

array([[0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 ],
       [0.11, 0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.2 ],
       [0.21, 0.22, 0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29, 0.3 ],
       [0.31, 0.32, 0.33, 0.34, 0.35, 0.36, 0.37, 0.38, 0.39, 0.4 ],
       [0.41, 0.42, 0.43, 0.44, 0.45, 0.46, 0.47, 0.48, 0.49, 0.5 ],
       [0.51, 0.52, 0.53, 0.54, 0.55, 0.56, 0.57, 0.58, 0.59, 0.6 ],
       [0.61, 0.62, 0.63, 0.64, 0.65, 0.66, 0.67, 0.68, 0.69, 0.7 ],
       [0.71, 0.72, 0.73, 0.74, 0.75, 0.76, 0.77, 0.78, 0.79, 0.8 ],
       [0.81, 0.82, 0.83, 0.84, 0.85, 0.86, 0.87, 0.88, 0.89, 0.9 ],
       [0.91, 0.92, 0.93, 0.94, 0.95, 0.96, 0.97, 0.98, 0.99, 1.  ]])

In [217]:
np.linspace(0,1,20)

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

In [222]:
#12
mat = np.arange(1,26).reshape(5,5)
mat

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [223]:
#13
mat[2:]

array([[11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [226]:
#14
mat[3,4]

20

In [237]:
#15
mat[:3,1].reshape(3,1)


array([[ 2],
       [ 7],
       [12]])

In [238]:
#16
mat[4,:]

array([21, 22, 23, 24, 25])

In [239]:
#17
mat[3:,:]

array([[16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [240]:
#18
mat.sum()

325

In [241]:
#19
mat.std()

7.211102550927978

In [243]:
#20
mat.sum(axis=0)

array([55, 60, 65, 70, 75])